feat: improve client schema generators

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -43,11 +43,12 @@ jobs:
         run: uv run pyright lilypad tests
 
       - name: Run Client Schemas Generator script
-        run: uv run scripts/generate_client_schema.py
+        run:  uv run scripts/generate_python_client_schema.py generate-python
 
       - name: Check for git diff
         run: |
-          git diff --exit-code lilypad/server/client || { echo "Error: Uncommitted changes found. Please run 'uv run scripts/generate_client_schema.py'"; exit 1; }
+          git diff --exit-code lilypad/server/client || { echo "Error: Uncommitted changes found. Please run 'uv run scripts/generate_python_client_schema.py generate-python'"; exit 1; }
+          git diff --exit-code client/src || { echo "Error: Uncommitted changes found. Please run './scripts/generate_typescript_client_schema.sh'"; exit 1; }
 
       - name: Minimize uv cache
         run: uv cache prune --ci
