fix: fix github actions

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -47,7 +47,7 @@ jobs:
 
       - name: Check for git diff
         run: |
-          git diff --exit-code lilypad/server/client || { echo "Error: Uncommitted changes found. Please run `uv run scripts/generate_client_schema.py`"; exit 1; }
+          git diff --exit-code lilypad/server/client || { echo "Error: Uncommitted changes found. Please run 'uv run scripts/generate_client_schema.py'"; exit 1; }
 
       - name: Minimize uv cache
         run: uv cache prune --ci
